### ISSUE TITLE
`instantiate_obj_at': method `method_missing' called on hidden T_DATA object

### ISSUE THREAD

**Issue by redood** [dmendel/bindata#59] opened 2015-05-01 17:58 UTC
I've been getting the following exception while trying to decode a big structure I have defined:

**/usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:279:in `instantiate_obj_at': method `method_missing' called on hidden T_DATA object (0x00000002660e20 flags=0xc klass=0x0) (NotImplementedError)**

I've been decoding data of this very structure many many times (for a couple of years) with no issue, and I only seem to notice this exception whenever I try to decode a large number of files (1000+) in a row. Adding a delay of about 10-15 seconds between each decode seems to workaround that issue, although obviously I'd prefer to just perform them as quickly as possible :)

This is on ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux].

/usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:279:in `instantiate_obj_at': method `method_missing' called on hidden T_DATA object (0x00000002660e20 flags=0xc klass=0x0) (NotImplementedError)
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:267:in `find_obj_for_name'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:164:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `collect'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `collect'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `collect'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `collect'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/array.rb:108:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/choice.rb:137:in `snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:165:in `block in snapshot'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/bindata-1.8.1/lib/bindata/struct.rb:163:in `snapshot'

**Comment by redood** [comment] 2015-05-01 18:01
BTW, the only other mention of this issue I seem to find is at:

http://irclog.whitequark.org/ruby-lang/2012-01-08

**Comment by dmendel** [comment] 2015-05-03 09:27
This looks like a ruby bug. Are you able to upgrade to a newer version of ruby? Perhaps invoking the garbage collector after each file is processed would work around it?

This doesn't look like something to be fixed with BinData. If you are able to reproduce it problem with ruby head and the latest BinData, then reopen this issue.

**Closed by dmendel** 2015-05-03 09:27 UTC
