### ISSUE TITLE
function set() has a bug

### ISSUE THREAD

**Issue by lilijreey** [dmendel/bindata#116] opened 2019-05-11 07:18 UTC
https://github.com/dmendel/bindata/blob/d50bc3d609e1715d1988b119167862d1eb9c4b6e/examples/tcp_ip.rb#L13

```ruby
a = MacAddr.new "10:08:b1:d6:9b:c1"
a.set("10:08:b1:d6:9b:c2")
a.to_i # is show "10:08:b1:d6:9b:c1" not c2
a.clear
a.a.set("10:08:b1:d6:9b:c2")
a.to_i # now is c2
```

**Comment by dmendel** [comment] 2019-05-11 14:34
Duplicate of #115

**Closed by dmendel** 2019-05-11 14:34 UTC
